server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/MateuszRasinski/config-repo-lab

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - bus-refresh
